export const SHOW_GROUP_MODAL = 'SHOW_GROUP_MODAL';
export const HIDE_GROUP_MODAL = 'HIDE_GROUP_MODAL';

export const SHOW_TASK_MODAL = 'SHOW_TASK_MODAL';
export const HIDE_TASK_MODAL = 'HIDE_TASK_MODAL';

export const SHOW_SUBTASK_MODAL = 'SHOW_SUBTASK_MODAL';
export const HIDE_SUBTASK_MODAL = 'HIDE_SUBTASK_MODAL';

export const HIDE_MODAL = 'HIDE_MODAL';