export const ADD_SUBTASK_REQ = 'ADD_SUBTASK_REQ';
export const UPDATE_SUBTASK_SUC = 'UPDATE_SUBTASK_SUC';
export const UPDATE_SUBTASK_FAIL = 'UPDATE_SUBTASK_FAIL';
export const UPDATE_SUBTASK_REQ = 'UPDATE_SUBTASK_REQ';